# Groupby in Python
- How to use pandas GroupBy operations on real-world data
- How the split-apply-combine chain of operations works
- How to decompose the split-apply-combine chain into steps
- How to categorize methods of a pandas GroupBy object based on their intent and result

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pydataset import data
import seaborn as sns

In [5]:
', '.join(data().title)

'Monthly Airline Passenger Numbers 1949-1960, Sales Data with Leading Indicator, Biochemical Oxygen Demand, Determination of Formaldehyde, Hair and Eye Color of Statistics Students, Effectiveness of Insect Sprays, Quarterly Earnings per Johnson & Johnson Share, Level of Lake Huron 1875-1972, Intercountry Life-Cycle Savings Data, Flow of the River Nile, Potency of Orchard Sprays, Results from an Experiment on Plant Growth, Reaction Velocity of an Enzymatic Reaction, Survival of passengers on the Titanic, The Effect of Vitamin C on Tooth Growth in Guinea Pigs, Student Admissions at UC Berkeley, Road Casualties in Great Britain 1969-84, UK Quarterly Gas Consumption, Accidental Deaths in the US 1973-1978, Violent Crime Rates by US State, Lawyers\' Ratings of State Judges in the US Superior Court, Personal Expenditure Data, Death Rates in Virginia (1940), Internet Usage per Minute, The World\'s Telephones, Passenger Miles on Commercial US Airlines, 1937-1960, New York Air Quality Measurements, Anscombe\'s Quartet of \'Identical\' Simple Linear Regressions, The Joyner-Boore Attenuation Data, The Chatterjee-Price Attitude Data, Quarterly Time Series of the Number of Australian Residents, Speed and Stopping Distances of Cars, Chicken Weights by Feed Type, Mauna Loa Atmospheric CO2 Concentration, Student\'s 3000 Criminals Data, Yearly Numbers of Important Discoveries, Smoking, Alcohol and (O)esophageal Cancer, Conversion Rates of Euro Currencies, Old Faithful Geyser Data, Freeny\'s Revenue Data, Infertility after Spontaneous and Induced Abortion, Edgar Anderson\'s Iris Data, Areas of the World\'s Major Landmasses, Luteinizing Hormone in Blood Samples, Longley\'s Economic Regression Data, Annual Canadian Lynx trappings 1821-1934, Michelson Speed of Light Data, Motor Trend Car Road Tests, Average Yearly Temperatures in New Haven, Average Monthly Temperatures at Nottingham, 1920-1939, Classical N, P, K Factorial Experiment, Occupational Status of Fathers and their Sons, Annual Precipitation in US Cities, Quarterly Approval Ratings of US Presidents, Vapor Pressure of Mercury as a Function of Temperature, Locations of Earthquakes off Fiji, Random Numbers from Congruential Generator RANDU, Lengths of Major North American Rivers, Measurements on Petroleum Rock Samples, Student\'s Sleep Data, Brownlee\'s Stack Loss Plant Data, Monthly Sunspot Data, from 1749 to "Present", Yearly Sunspot Data, 1700-1988, Monthly Sunspot Numbers, 1749-1983, Swiss Fertility and Socioeconomic Indicators (1888) Data, Yearly Treering Data, -6000-1979, Girth, Height and Volume for Black Cherry Trees, Populations Recorded by the US Census, Topographic Information on Auckland\'s Maunga Whau Volcano, The Number of Breaks in Yarn during Weaving, Average Heights and Weights for American Women, Monthly Excess Returns, Delay in AIDS Reporting in England and Wales, Failures of Air-conditioning Equipment, Failures of Air-conditioning Equipment, Car Speeding and Warning Signs, Remission Times for Acute Myelogenous Leukaemia, Population of U.S. Cities, Spatial Location of Bramble Canes, Smoking Deaths Among Doctors, Calcium Uptake Data, Sugar-cane Disease Data, Simulated Manufacturing Process Data, Weight Data for Domestic Cats, Position of Muscle Caveolae, CD4 Counts for HIV-Positive Patients, Channing House Data, Population of U.S. Cities, Genetic Links to Left-handedness, Number of Flaws in Cloth, Carbon Monoxide Transfer, Dates of Coal Mining Disasters, Darwin\'s Plant Height Differences, Cardiac Data for Domestic Dogs, Incidence of Down\'s Syndrome in British Columbia, Behavioral and Plumage Characteristics of Hybrid Ducks, Counts of Balsam-fir Seedlings, Head Dimensions in Brothers, Acceleration Due to Gravity, Acceleration Due to Gravity, Failure Time of PET Film, Jura Quartzite Azimuths on Islay, Average Heights of the Rio Negro river at Manaus, Survival from Malignant Melanoma, Data from a Simulated Motorcycle Accident, Neurophysiological Point Process Data, Toxicity of Nitrofen in Aquatic Systems, Nodal Involvement in Prostate Cancer, Nuclear Power Station Construction Data, Neurotransmission in Guinea Pig Brains, Animal Survival Times, Pole Positions of New Caledonian Laterites, Cancer Remission and Cell Activity, Water Salinity and River Discharge, Survival of Rats after Radiation Doses, Tau Particle Decay Modes, Tuna Sighting Data, Urine Analysis Data, Australian Relative Wool Prices, data from Section 1.19, data from Section 1.9, data from Exercise 13.1, p418, data from Exercise 4.7, p122, data from Exercise 5.8, p147, data from Section 1.18, data from Section 1.14, data from Section 1.3, data from Exercise 7.7, p223, data from Section 1.5, data from Section 1.6, data from Section 1.16, data from Section 1.2, data from Exercise 7.6, p222, data from Section 1.10, data from Section 1.4, Data on 38 individuals using a kidney dialysis machine, data from Section 1.7, data from Section 1.8, data from Exercise 4.4, p120, data from Section 1.13, data from Section 1.15, data from Exercise 7.13, p225, data from Section 1.12, data from Exercise 5.6, p146, data from Section 1.11, data from Exercise 7.14, p225, Brain and Body Weights for 65 Species of Land Animals, Crohn\'s Disease Adverse Events Data, NOx Air Pollution Data, Siegel\'s Exact Fit Example Data, Aircraft Data, Air Quality Data, Alcohol Solubility in Water Data, Daily Means of NOx (mono-nitrogen oxides) in air, Campbell Bushfire Data, Insect Damages on Carrots, Cloud point of a Liquid, Coleman Data Set, Condroz Data, Cushny and Peebles Prolongation of Sleep Data, Delivery Time Data, Education Expenditure Data, Epilepsy Attacks Data Set, Example Data of Antille and May - for Simple Regression, Food Stamp Program Participation, Hawkins, Bradu, Kass\'s Artificial Data, Heart Catherization Data, Waterflow Measurements of Kootenay River in Libby and Newgate, Lactic Acid Concentration Measurement Data, Daudin\'s Milk Composition Data, Pension Funds Data, Phosphorus Content Data, Pilot-Plant Data, Possum Diversity Data, Pulp Fiber and Paper Data, Satellite Radar Image Data from near Munich, Salinity Data, Hertzsprung-Russell Diagram Data of Star Cluster CYG OB1, Number of International Calls from Belgium, Toxicity of Carboxylic Acids Data, Vaso Constriction Skin Data Set, Wagner\'s Hannover Employment Growth Data, Modified Data on Wood Specific Gravity, American Math Society Survey Data, Experimenter Expectations, Moral Integration of American Cities, U. S. State Public-School Expenditures, Methods of Teaching Reading Comprehension, Canadian Women\'s Labour-Force Participation, Exercise Histories of Eating-Disordered and Control Subjects, Fraudulent Data on IQs of Twins Raised Apart, Canadian Population Data, Voting Intentions in the 1988 Chilean Plebiscite, The 1907 Romanian Peasant Rebellion, Cowles and Davis\'s Data on Volunteering, Self-Reports of Height and Weight, Davis\'s Data on Drive for Thinness, Minnesota Wolf Depredation Data, Duncan\'s Occupational Prestige Data, The 1980 U.S. Census Undercount, Florida County Voting, Crowding and Crime in U. S. Metropolitan Areas, Format Effects on Recall, Data on Depression, Refugee Appeals, Anonymity and Cooperation, Canadian Crime-Rates Time Series, Highway Accidents, Data on Infant-Mortality, Contrived Collinear Data, Canadian Interprovincial Migration Data, Status, Authoritarianism, and Conformity, U.S. Women\'s Labor-Force Participation, O\'Brien and Kaiser\'s Repeated-Measures Data, Interlocking Directorates Among Major Canadian Firms, Chemical Composition of Pottery, Prestige of Canadian Occupations, Four Regression Datasets, Fertility and Contraception, Survey of Labour and Income Dynamics, Agricultural Production in Mazulu Village, Salaries for Professors, Soil Compositions of Physical and Chemical Characteristics, Education and Related Statistics for the U.S. States, Transaction data, GDP and Infant Mortality, Population of the United States, Vocabulary and Education, Weight Loss Data, Canadian Women\'s Labour-Force Participation, Wool data, European Union Agricultural Workforces, Attributes of Animals, Subset of C-horizon of Kola Data, Flower Characteristics, Plant Species Traits Data, Isotopic Composition Plutonium Batches, Ruspini Data, Votes for Republican Candidate in Presidential Elections, Bivariate Data Set with 3 Clusters, affairs, azcabgptca, azdrg112, azpro, azprocedure, badhealth, fasttrakg, fishing, lbw, lbwgrp, loomis, mdvis, medpar, nuts, rwm, rwm1984, rwm5yr, ships, smoking, titanic, titanicgrp, Ship Accidents, Cost for U.S. Airlines, Air Quality for Californian Metropolitan Areas, Unemployement of Blue Collar Workers, Bids Received By U.S. Firms, Budget Share of Food for Spanish Households, Budget Shares for Italian Households, Budget Shares of British Households, Wages in Belgium, Earnings from the Current Population Survey, Growth of CRAN, Stock Market Data, Stated Preferences for Car Choice, The California Test Score Data Set, Choice of Brand for Catsup, Cigarette Consumption, The Cigarette Consumption Panel Data Set, Sales Data of Men\'s Fashion Stores, Prices of Personal Computers, Choice of Brand for Crakers, Crime in North Carolina, DM Dollar Exchange Rate, Pricing the C\'s of Diamond Stones, Number of Doctor Visits, Doctor Visits in Australia, Contacts With Medical Doctor, Earnings for Three Age Groups, Cost Function for Electricity Producers, Extramarital Affairs Data, Drunk Driving Laws and Traffic Deaths, Choice of Fishing Mode, Exchange Rates of US Dollar Against Other Currencies, Data from the Television Game Show Friend Or Foe ?, Daily Observations on Exchange Rates of the US Dollar Against Other Currencies, Gasoline Consumption, Wage Datas, Grunfeld Investment Data, Heating and Cooling System Choice in Newly Built Houses in California, Health Insurance and Hours Worked By Wives, The Boston HDMA Data Set, Heating System Choice in California Houses, Hedonic Prices of Cencus Tracts in Boston, Sales Prices of Houses in the City of Windsor, Ice Cream Consumption, Economic Journals Dat Set, Willingness to Pay for the Preservation of the Kakadu National Park, Choice of Brand for Ketchup, Klein\'s Model I, Wages and Hours Worked, Belgian Firms, The Massashusets Test Score Data Set, Wages and Education of Young Males, Level of Calculus Attained for Students Taking Advanced Micro-economics, Structure of Demand for Medical Care, Production for SIC 33, Mode Choice, Data to Study Travel Mode Choice, International Expansion of U.S. Mofa\'s (majority-owned Foreign Affiliates in Fire (finance, Insurance and Real Estate), Labor Supply Data, Municipal Expenditure Data, Willingness to Pay for the Preservation of the Alentejo Natural Park, Cost Function for Electricity Producers, 1955, Visits to Physician Office, Oil Investment, Panel Survey of Income Dynamics, Labor Force Participation, Dynamic Relation Between Patents and R&D, Patents, R&D and Technological Spillovers for a Panel of Firms, Pound-dollar Exchange Rate, Us States Production, Return to Schooling, Returns on Standard & Poor\'s 500 Index, Wages and Schooling, Visits to Lake Somerville, Effects on Learning of Small Class Sizes, Strike Duration Data, Strikes Duration, Number of Strikes in Us Manufacturing, The Penn Table, Households Tobacco Budget Share, Stated Preferences for Train Traveling, Statewide Data on Transportation Equipment Manufacturing, Evaluating Treatment Effect of Training on Earnings, Choice of Brand for Tuna, US Finance Industry Profits, Official Secrecy of the United States Government, Standard abbreviations for states of the United States, Number of Words in US Tax Law, Unemployment Duration, Unemployment Duration, Provision of University Teaching and Research, Medical Expenses in Viet-nam (household Level), Medical Expenses in Viet-nam (individual Level), Panel Datas of Individual Wages, Wages, Experience and Schooling, Wife Working Hours, Yen-dollar Exchange Rate, Choice of Brand for Yogurts, Countries in Banking Crises, Income Inequality in the US, Names with Character Set Problems, Political knowledge in the US and Europe, A study of Parkinson\'s disease and APOE, LRRK2, SNCA makers, ALDH2 markers and Alcoholism, APOE/APOC1 markers and Alzheimer\'s, Cystic fibrosis data, Crohn\'s disease data, Friedreich Ataxia data, A case-control data involving four SNPs with missing genotype, The HLA data, An example data for Manhattan plot with annotation, An example pedigree data, An example pedigree, A study of Parkinson\'s disease and MAO gene, Example data for ACEnucfam, An example data for Manhattan plot, A study of Alzheimer\'s disease with eight SNPs and APOE, Prices of 50,000 round cut diamonds, US economic time series., Midwest demographics., Movie information and user ratings from IMDB.com., Fuel economy data from 1999 and 2008 for 38 popular models of car, An updated and expanded version of the mammals sleep dataset., Terms of 10 presidents from Eisenhower to Bush W., Vector field of seal movements., Arbuthnot\'s data on male and female birth ratios in London from 1629-1710., Bowley\'s data on values of British and Irish trade, 1855-1899, Cavendish\'s Determinations of the Density of the Earth, Chest measurements of 5738 Scottish Militiamen, Cushny-Peebles Data: Soporific Effects of Scopolamine Derivatives, Cushny-Peebles Data: Soporific Effects of Scopolamine Derivatives, Edgeworth\'s counts of dactyls in Virgil\'s Aeneid, Elderton and Pearson\'s (1910) data on drinking and wages, Waite\'s data on Patterns in Fingerprints, Galton\'s data on the heights of parents and their children, Galton\'s data on the heights of parents and their children, by child, Data from A.-M. Guerry, "Essay on the Moral Statistics of France", W. Stanley Jevons\' data on numerical discrimination, van Langren\'s Data on Longitude Distance between Toledo and Rome, van Langren\'s Data on Longitude Distance between Toledo and Rome, Macdonell\'s Data on Height and Finger Length of Criminals, used by Gosset (1908), Macdonell\'s Data on Height and Finger Length of Criminals, used by Gosset (1908), Michelson\'s Determinations of the Velocity of Light, Michelson\'s Determinations of the Velocity of Light, Data from Minard\'s famous graphic map of Napoleon\'s march on Moscow, Data from Minard\'s famous graphic map of Napoleon\'s march on Moscow, Data from Minard\'s famous graphic map of Napoleon\'s march on Moscow, Florence Nightingale\'s data on deaths from various causes in the Crimean War, Latitudes and Longitudes of 39 Points in 11 Old Maps, Pearson and Lee\'s data on the heights of parents and children classified by gender, Polio Field Trials Data, Parent-Duchatelet\'s time-series data on the number of prostitutes in Paris, Trial of the Pyx, Statistics of Deadly Quarrels, John Snow\'s map and data on the 1854 London Cholera outbreak, John Snow\'s map and data on the 1854 London Cholera outbreak, John Snow\'s map and data on the 1854 London Cholera outbreak, John Snow\'s map and data on the 1854 London Cholera outbreak, Playfair\'s Data on Wages and the Price of Wheat, Playfair\'s Data on Wages and the Price of Wheat, Student\'s (1906) Yeast Cell Counts, Student\'s (1906) Yeast Cell Counts, Darwin\'s Heights of Cross- and Self-fertilized Zea May Pairs, Yield data from a Minnesota barley trial, Atmospheric environmental conditions in New York City, Engine exhaust fumes from burning ethanol, Melanoma skin cancer incidence, Heights of New York Choral Society singers, Australian AIDS Survival Data, Brain and Body Weights for 28 Species, Housing Values in Suburbs of Boston, Data from 93 Cars on Sale in the USA in 1993, Diagnostic Tests on Patients with Cushing\'s Syndrome, DDT in Kale, Level of GAG in Urine of Children, Numbers of Car Insurance claims, Survival from Malignant Melanoma, Tests of Auditory Perception in Children with OME, Diabetes in Pima Indian Women, Diabetes in Pima Indian Women, Diabetes in Pima Indian Women, Blood Pressure in Rabbits, Accelerated Testing of Tyre Rubber, Returns of the Standard and Poors 500, Growth Curves for Sitka Spruce Trees in 1988, Growth Curves for Sitka Spruce Trees in 1989, AFM Compositions of Aphyric Skye Lavas, Effect of Swedish Speed Limits on Accidents, Nutritional and Marketing Information on US Cereals, The Effect of Punishment Regimes on Crime Rates, Veteran\'s Administration Lung Cancer Trial, Determinations of Nickel Content, Accidental Deaths in the US 1973-1978, Anorexia Data on Weight Change, Presence of Bacteria after Drug Treatments, Body Temperature Series of Beaver 1, Body Temperature Series of Beaver 2, Biopsy Data on Breast Cancer Patients, Risk Factors Associated with Low Infant Birth Weight, Data from a cabbage field trial, Colours of Eyes and Hair of People in Caithness, Anatomical Data from Domestic Cats, Heat Evolved by Setting Cements, Copper in Wholemeal Flour, Co-operative Trial in Analytical Chemistry, Performance of Computer CPUs, Morphological Measurements on Leptograpsus Crabs, Monthly Deaths from Lung Diseases in the UK, Deaths of Car Drivers in Great Britain 1969-84, Foraging Ecology of Bald Eagles, Seizure Counts for Epileptics, Ecological Factors in Farm Management, Measurements of Forensic Glass Fragments, Forbes\' Data on Boiling Points in the Alps, Velocities for 82 Galaxies, Remission Times of Leukaemia Patients, Rat Genotype Data, Old Faithful Geyser Data, Line Transect of Soil in Gilgai Territory, Record Times in Scottish Hill Races, Frequency Table from a Copenhagen Housing Conditions Survey, Yields from a Barley Field Trial, Survival Times and White Blood Counts for Leukaemia Patients, Brain and Body Weights for 62 Species of Land Mammals, Data from a Simulated Motorcycle Accident, Age of Menarche in Warsaw, Michelson\'s Speed of Light Data, Minnesota High School Graduates of 1938, Accelerated Life Testing of Motorettes, Effect of Calcium Chloride on Muscle Contraction in Rat Hearts, Newcomb\'s Measurements of the Passage Time of Light, Eighth-Grade Pupils in the Netherlands, Classical N, P, K Factorial Experiment, US Naval Petroleum Reserve No. 1 data, Data from an Oats Field Trial, The Painter\'s Data of de Piles, N. L. Prater\'s Petrol Refinery Data, Absenteeism from School in Rural New South Wales, Road Accident Deaths in US States, Numbers of Rotifers by Fluid Density, Ships Damage Data, Percentage of Shrimp in Shrimp Cocktail, Space Shuttle Autolander Problem, Snail Mortality Data, The Saturated Steam Pressure Data, The Stormer Viscometer Data, Student Survey Data, Synthetic Classification Problem, Synthetic Classification Problem, Spatial Topographic Data, Counts of Waders at 15 Sites in South Africa, House Insulation: Whiteside\'s Data, Weight Loss Data from an Obese Patient, Cigarette Consumption, Crime in North Carolina, Employment and Wages in the United Kingdom, Gasoline Consumption, Grunfeld\'s Investment Data, Hedonic Prices of Census Tracts in the Boston Area, Wages and Hours Worked, Wages and Education of Young Males, US States Production, Employment and Wages in Spain, The Penn World Table, v. 5, Panel Data of Individual Wages, Yearly batting records for all major league baseball players, Political opinion polls in Australia, 2004-07, elections to Australian House of Representatives, 1949-2007, Batting Averages for 18 major league baseball players, 1970, Voter turnout experiment, using Rock The Vote ads, 1992 United Kingdom electoral returns, Absentee and Machine Ballots in Pennsylvania State Senate Races, Applications to a Political Science PhD Program, article production by graduate students in biochemistry Ph.D. programs, California Congressional Districts in 2006, U.S. Senate vote on the use of force against Iraq, 2002., Interviewer ratings of respondent levels of political information, elections for U.S. President, 1932-2012, by state, Prussian army horse kick data, cross national rates of trade union density, Reports of voting in the 1992 U.S. Presidential election., Sensory data fr

In [9]:
linkdata1 = 'https://theunitedstates.io/congress-legislators/legislators-current.csv'
linkdata2 = 'https://theunitedstates.io/congress-legislators/legislators-historical.csv'
df = pd.read_csv(linkdata2)
df.head()
#https://github.com/unitedstates/congress-legislators?tab=readme-ov-file

,last_name,first_name,middle_name,suffix,nickname,full_name,birthday,gender,type,state,...,opensecrets_id,lis_id,fec_ids,cspan_id,govtrack_id,votesmart_id,ballotpedia_id,washington_post_id,icpsr_id,wikipedia_id
0,Bassett,Richard,NaN,NaN,NaN,NaN,1745-04-02,M,sen,DE,...,NaN,NaN,NaN,NaN,401222,NaN,NaN,NaN,507.0,Richard Bassett (Delaware politician)
1,Bland,Theodorick,NaN,NaN,NaN,NaN,1742-03-21,M,rep,VA,...,NaN,NaN,NaN,NaN,401521,NaN,NaN,NaN,786.0,Theodorick Bland (congressman)
2,Burke,Aedanus,NaN,NaN,NaN,NaN,1743-06-16,M,rep,SC,...,NaN,NaN,NaN,NaN,402032,NaN,NaN,NaN,1260.0,Aedanus Burke
3,Carroll,Daniel,NaN,NaN,NaN,NaN,1730-07-22,M,rep,MD,...,NaN,NaN,NaN,NaN,402334,NaN,NaN,NaN,1538.0,Daniel Carroll
4,Clymer,George,NaN,NaN,NaN,NaN,1739-03-16,M,rep,PA,...,NaN,NaN,NaN,NaN,402671,NaN,NaN,NaN,1859.0,George Clymer

In [10]:
df.columns

Index(['last_name', 'first_name', 'middle_name', 'suffix', 'nickname',
       'full_name', 'birthday', 'gender', 'type', 'state', 'district',
       'senate_class', 'party', 'url', 'address', 'phone', 'contact_form',
       'rss_url', 'twitter', 'twitter_id', 'facebook', 'youtube', 'youtube_id',
       'mastodon', 'bioguide_id', 'thomas_id', 'opensecrets_id', 'lis_id',
       'fec_ids', 'cspan_id', 'govtrack_id', 'votesmart_id', 'ballotpedia_id',
       'washington_post_id', 'icpsr_id', 'wikipedia_id'],
      dtype='object')

In [11]:
cols1 = ['last_name','first_name', 'birthday', 'gender', 'type', 'state', 'party']
df1 = df[cols1]
df1.head()

  last_name  first_name    birthday gender type state                party
0   Bassett     Richard  1745-04-02      M  sen    DE  Anti-Administration
1     Bland  Theodorick  1742-03-21      M  rep    VA                  NaN
2     Burke     Aedanus  1743-06-16      M  rep    SC                  NaN
3   Carroll      Daniel  1730-07-22      M  rep    MD                  NaN
4    Clymer      George  1739-03-16      M  rep    PA                  NaN

In [17]:
df1.groupby('state').size().sort_values(ascending=False).head(5)
#top 5 status

state
NY    1479
PA    1057
OH     682
IL     493
VA     435
dtype: int64

In [22]:
#by default, state values become the index, if it is required in column
#df1.groupby('state', as_index=False).size()
df1.groupby('state', as_index=False).size().sort_values(by='size',ascending=False).head(5)
#now it has rangeindex

   state  size
37    NY  1479
42    PA  1057
38    OH   682
17    IL   493
51    VA   435

In [24]:
#skip sort by state key
df1.groupby('state', sort=False).size().head(10)

state
DE      97
VA     435
SC     252
MD     306
PA    1057
MA     427
NJ     361
GA     319
NY    1479
NC     360
dtype: int64

In [25]:
# air quality
airquality = data('airquality')
airquality.head()

   Ozone  Solar.R  Wind  Temp  Month  Day
1   41.0    190.0   7.4    67      5    1
2   36.0    118.0   8.0    72      5    2
3   12.0    149.0  12.6    74      5    3
4   18.0    313.0  11.5    62      5    4
5    NaN      NaN  14.3    56      5    5